image: python:3.6

stages:
  - test

test_e2e_admin:
  stage: test
  script:
    - nosetests -v tests/e2e/test_e2e_admin.py --nocapture

test_e2e_user:
  stage: test
  script:
    - nosetests -v tests/e2e/test_e2e_user.py --nocapture

integration_test:
  stage: test
  script:
    - nosetests -v tests.command


before_script:
  - pip install -r requirements-dev.txt
