image: python:3.6

stages:
  - tests

e2e_test:
  stage: tests
  script:
    - PYTHONPATH=$PWD/tests nosetests -v tests.e2e

integration_test:
  stage: tests
  script:
    - nosetests -v tests.command


before_script:
  - pip install -r requirements-dev.txt
  - pip install covid-util
