image: python:3.6

stages:
  - tests

test_e2e_admin:
  stage: tests
  script:
    - nosetests -v tests/e2e/test_e2e_admin.py

test_e2e_user:
  stage: tests
  script:
    - nosetests -v tests/e2e/test_e2e_user.py

integration_test:
  stage: tests
  script:
    - nosetests -v tests.command


before_script:
  - pip install -r requirements-dev.txt
